meta_product_name: "Tata Monique"
meta_title: "Tata Monique - Finie la phobie administrative "
meta_description: "L'outil personnalisé qui simplifie vos démarches administratives grâce à une technologie avancée"
meta_image: "home_page_zen1.png" # should exist in `app/assets/images/`
